<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions
        xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
        xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
        xmlns:tns="http://org.ecodex.backend/"
        name="backendService"
        targetNamespace="http://org.ecodex.backend/">

    <wsdl:types>

        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://org.ecodex.backend/" schemaLocation="backend.xsd"/>
        </schema>
    </wsdl:types>

    <wsdl:message name="sendSuccess">
        <wsdl:part element="tns:sendSuccess" name="sendSuccess">
        </wsdl:part>
    </wsdl:message>
    <wsdl:message name="sendSuccessResponse">
        <wsdl:part element="tns:sendSuccessResponse" name="sendSuccessResponse">
        </wsdl:part>
    </wsdl:message>
    <wsdl:message name="sendSuccessFault">
        <wsdl:part element="tns:FaultDetail" name="sendSuccessFault">
        </wsdl:part>
    </wsdl:message>

    <wsdl:portType name="BackendInterface">
        <wsdl:operation name="sendSuccess">
            <wsdl:input message="tns:sendSuccess" name="sendSuccess">
            </wsdl:input>
            <wsdl:output message="tns:sendSuccessResponse" name="sendSuccessResponse">
            </wsdl:output>
            <wsdl:fault message="tns:sendSuccessFault" name="sendSuccessFault">
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="BackendServiceSoapBinding" type="tns:BackendInterface">
        <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="sendSuccess">
            <soap12:operation soapAction="" style="document"/>
            <wsdl:input name="sendSuccess">
                <soap12:body parts="sendSuccess" use="literal"/>
            </wsdl:input>
            <wsdl:output name="sendSuccessResponse">
                <soap12:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="sendSuccessFault">
                <soap12:fault name="sendSuccessFault" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="BackendService">
        <wsdl:port binding="tns:BackendServiceSoapBinding" name="BACKEND_PORT">
            <soap12:address location="http://localhost:8080/backend"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>