---
excludes:
  paths:
  - pattern: "Plugin-FS/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Not included in distributed build artifacts."

  - pattern: "Plugin-JMS/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Not included in distributed build artifacts."

  - pattern: "Weblogic/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Not included in distributed build artifacts."

  - pattern: "Wildfly/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Not included in distributed build artifacts."

  - pattern: "Core/Domibus-MSH-swagger/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Not included in distributed build artifacts."

  - pattern: "Core/Domibus-MSH-distribution/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Not included in distributed build artifacts."    

  - pattern: "Domibus-DSS/domibus-dss-test/**"
    reason: "TEST_OF"
    comment: "This directory contains tests."

  - pattern: "Core/Domibus-MSH-selenium-ui-tests/**"
    reason: "TEST_OF"
    comment: "This directory contains tests."

  - pattern: "Core/Domibus-MSH-soapui-tests/**"
    reason: "TEST_OF"
    comment: "This directory contains tests."

  - pattern: "Core/Domibus-MSH-test/**"
    reason: "TEST_OF"
    comment: "This directory contains tests."

  - pattern: "Plugin-WS/Domibus-default-ws-plugin-backend-ws-test/**"
    reason: "TEST_OF"
    comment: "This directory contains tests."

  scopes:
  - pattern: "checkstyle"
    reason: "BUILD_DEPENDENCY_OF"
    comment: "Packages for code styling checks (testing) only."

  - pattern: "devDependencies"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."

  - pattern: "jacocoAgent"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for code coverage (testing) only."

  - pattern: "jacocoAnt"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for code coverage (testing) only."

  - pattern: "test.*"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for testing only."

  - pattern: "annotationProcessor"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."

  - pattern: "compileClasspath"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."

  - pattern: "compileOnly"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."

resolutions:
  rule_violations:
    - message: "copyleft-strong license GPL-2.0-only in Maven:jakarta.xml.bind:jakarta.xml.bind-api:2.3.3."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The files meant by this license are all under an exception."

    - message: "copyleft-strong license EUPL-1.2 in.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "EUPL-1.2 is the main license of the project and therefore not an issue."

    - message: "copyleft-strong license GPL-2.0-only WITH Universal-FOSS-exception-1.0 in Maven:com.hazelcast:hazelcast-spring:5.3.6."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "Not an issue due to the exception."

    - message: "copyleft-strong license GPL-2.0-only WITH Universal-FOSS-exception-1.0 in Maven:com.hazelcast:hazelcast:5.3.6."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "Not an issue due to the exception."

    - message: "property:network-clause license EUPL-1.1 in.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "EUPL-1.2 is the main license of the project and therefore not an issue. All EUPL-1.1 matches are under EUPL-1.2."

    - message: "property:network-clause license EUPL-1.2 in.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "EUPL-1.2 is the main license of the project and therefore not an issue."

    - message: "copyleft-strong license EUPL-1.1 in.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "EUPL-1.2 is the main license of the project and therefore not an issue. All EUPL-1.1 matches are under EUPL-1.2."

curations:
  license_findings:
  - path: "Core/Domibus-MSH-api/src/main/java/eu/domibus/api/util/BCryptPasswordHash.java"
    detected_license: "EUPL-1.1"
    reason: "INCORRECT"
    comment: "Incorrect scanner match."
    concluded_license: "EUPL-1.2"

license_choices:
  repository_license_choices:
    - given: "MIT OR GPL-2.0-only"
      choice: "MIT"
    - given: "MIT OR BSD-3-Clause OR GPL-2.0-only"
      choice: "MIT"
    - given: "MIT OR GPL-1.0-or-later"
      choice: "MIT"
    - given: "MIT OR AFL-2.1"
      choice: "MIT"
    - given: "CDDL-1.1 OR GPL-2.0-only WITH Classpath-exception-2.0"
      choice: "CDDL-1.1"
    - given: "CDDL-1.0 OR GPL-2.0-only"
      choice: "CDDL-1.0"
