---
excludes:
  paths:
    - pattern: ".mvn/wrapper/**"
      reason: "BUILD_TOOL_OF"
      comment: "This is a build tool."

    - pattern: "Plugin-FS/**"
      reason: "OPTIONAL_COMPONENT_OF"
      comment: "Not included in distributed build artifacts."

    - pattern: "Plugin-JMS/**"
      reason: "OPTIONAL_COMPONENT_OF"
      comment: "Not included in distributed build artifacts."

    - pattern: "Plugin-WS/Domibus-default-ws-plugin-backend-ws-test/**"
      reason: "TEST_OF"
      comment: "This directory contains tests."

    - pattern: "Weblogic/**"
      reason: "OPTIONAL_COMPONENT_OF"
      comment: "Not included in distributed build artifacts."

    - pattern: "Wildfly/**"
      reason: "OPTIONAL_COMPONENT_OF"
      comment: "Not included in distributed build artifacts."

    - pattern: "license/**"
      reason: "OTHER"
      comment: "This directory includes 3rd party license files."

    - pattern: "third-party/**"
      reason: "DOCUMENTATION_OF"
      comment: "The directory contains third party license notices. The package itself does not contain the files referenced in the license notice."

    - pattern: "Core/Domibus-MSH-distribution/**"
      reason: "OPTIONAL_COMPONENT_OF"
      comment: "Not included in distributed build artifacts."

    - pattern: "Core/Domibus-MSH-soapui-tests/**"
      reason: "TEST_OF"
      comment: "This directory contains tests."

    - pattern: "Core/Domibus-MSH-swagger/**"
      reason: "OPTIONAL_COMPONENT_OF"
      comment: "Not included in distributed build artifacts."

    - pattern: "Core/Domibus-MSH-test/**"
      reason: "TEST_OF"
      comment: "This directory contains tests."

    - pattern: "Core/Domibus-MSH-test-common/**"
      reason: "TEST_OF"
      comment: "This directory contains tests."

    - pattern: "**/src/test/**"
      reason: "TEST_OF"
      comment: "This directory contains unit tests."

    - pattern: ".ort.yml"
      reason: "DOCUMENTATION_OF"
      comment: "The file is a oss review toolkit configuration file."

    - pattern: "Notice.md"
      reason: "OTHER"
      comment: "This file includes a list of 3rd party libraries."

    - pattern: "THIRD-PARTY.txt"
      reason: "OTHER"
      comment: "This file includes a list of 3rd party libraries."

    - pattern: "mvnw"
      reason: "BUILD_TOOL_OF"
      comment: "This is a build tool."

    - pattern: "mvnw.cmd"
      reason: "BUILD_TOOL_OF"
      comment: "This is a build tool."

  scopes:
    - pattern: "checkstyle"
      reason: "BUILD_DEPENDENCY_OF"
      comment: "Packages for code styling checks (testing) only."

    - pattern: "devDependencies"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for development only."

    - pattern: "jacocoAgent"
      reason: "TEST_DEPENDENCY_OF"
      comment: "Packages for code coverage (testing) only."

    - pattern: "jacocoAnt"
      reason: "TEST_DEPENDENCY_OF"
      comment: "Packages for code coverage (testing) only."

    - pattern: "test.*"
      reason: "TEST_DEPENDENCY_OF"
      comment: "Packages for testing only."

    - pattern: "annotationProcessor"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for development only."

    - pattern: "compileClasspath"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for development only."

    - pattern: "compileOnly"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for development only."

resolutions:
  rule_violations:
    - message: ".*EUPL-1.2.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "EUPL-1.2 is the main license of the project."
    - message: ".*EUPL-1.1.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "EUPL-1.2 is the main license of the project and EUPL-1.1 is upward compatible."
    - message: "copyleft-LGPL license LGPL-2.1-only in Maven:org.niis:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The package's main license is EUPL-1.2, and LGPL-2.1 is compatible with the main license."
    - message: "copyleft-LGPL license LGPL-2.1-or-later in Maven:org.niis:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The package's main license is EUPL-1.2, and LGPL-2.1 is compatible with the main license."
    - message: "copyleft-LGPL license LGPL-2.1-or-later in Maven:com.mchange:c3p0:0.9.5.4."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The package's main license is EUPL-1.2, and LGPL-2.1 is compatible with the main license."
    - message: "copyleft-LGPL license LGPL-2.1-or-later in Maven:com.mchange:mchange-commons-java:0.2.15."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The package's main license is EUPL-1.2, and LGPL-2.1 is compatible with the main license."
    - message: "free-restricted license LicenseRef-scancode-hazelcast-community-1.0 in Maven:com.hazelcast:hazelcast.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "As the NIIS application doesn't compete with Hazelcast offering, the license conditions are satisfied."
    - message: ".*LicenseRef-scancode-sun-jsr-spec-04-2006.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "A specification license."
    - message: "proprietary-free license LicenseRef-scancode-iptc-2006 in Maven:org.apache.tika:tika-core:2.7.0."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "A specification license."
    - message: ".*LicenseRef-scancode-efsl-1.0.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "A specification license."
    - message: "copyleft-strong license GPL-1.0-or-later in Maven:org.jvnet.staxex:stax-ex:1.8.3."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file. The package contains only BSD-3-Clause files, while referenced licenses likely apply to dependencies or external components."
    - message: "copyleft-strong license GPL-1.0-or-later in Maven:com.sun.xml.fastinfoset:FastInfoset:1.2.18."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file. The package contains only Apache-2.0 files, while referenced licenses likely apply to dependencies or external components."
    - message: "copyleft-strong license GPL-1.0-or-later in Maven:com.sun.istack:istack-commons-runtime:3.0.12."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file. The package contains only BSD-3-Clause files, while referenced licenses likely apply to dependencies or external components."
    - message: "copyleft-strong license GPL-2.0-only in Maven:javax.jws:jsr181-api:1.0-MR1."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The files in the package have no license."
    - message: "copyleft-strong license GPL-2.0-only in Maven:javax.jws:jsr181-api:1.0-MR1."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The files in the package have no license."
    - message: "copyleft-strong license GPL-2.0-or-later WITH Autoconf-exception-2.0 in Maven:antlr:antlr:2.7.7."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The license requires distribution under GPL terms but provides an exception for projects using Autoconf-generated configuration scripts, permitting them to be licensed under the same terms as the rest of the project."
    - message: "copyleft-strong license GPL-2.0-only in Maven:javax.jws:jsr181-api:1.0-MR1."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The declared license is actually CDDL-1.0 OR GPL-2.0-only WITH Autoconf-exception-2.0. The license requires distribution under GPL terms but provides an exception for projects using Autoconf-generated configuration scripts, permitting them to be licensed under the same terms as the rest of the project."
    - message: "copyleft-strong license GPL-2.0-or-later in Maven:antlr:antlr:2.7.7."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The file is deemed to be separate and distinct from the other parts of the package and therefore seen as mere aggregation. The license obligations of GPL-2.0-or-later do not cover the whole."
    - message: "copyleft-LGPL license LGPL-3.0-only in Maven:org.niis:harmony:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file."
    - message: "copyleft-file-level license CDDL-1.0 in Maven:org.niis:harmony:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file."
    - message: "copyleft-file-level license EPL-2.0 in Maven:org.niis:harmony:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file."
    - message: "copyleft-file-level license MPL-1.1 in Maven:org.niis:harmony:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file."
    - message: "copyleft-file-level license MPL-2.0 in Maven:org.niis:harmony:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file."
    - message: "copyleft-file-level license CDDL-1.1 in Maven:org.niis:harmony:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file."
    - message: "copyleft-module-level license EPL-1.0 in Maven:org.niis:harmony:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file."
    - message: "copyleft-module-level license GPL-2.0-only WITH Classpath-exception-2.0 in Maven:org.niis:harmony:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file."
    - message: "copyleft-strong license GPL-2.0-or-later WITH Classpath-exception-2.0 in Maven:org.niis:harmony:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file."
    - message: "Strong copyleft in open source project code GPL-2.0-or-later WITH Classpath-exception-2.0 in Maven:org.niis:harmony:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file."
    - message: "copyleft-module-level license GPL-2.0-only WITH Linux-syscall-note in Maven:org.niis:harmony:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "License notice file."
    - message: "Unhandled license LicenseRef-scancode-un-cefact-2016 in Maven:org.niis.dynamic-discovery:dynamic-discovery-client:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The license LicenseRef-scancode-un-cefact-2016 license allows redistribution if the copyright notice and license text are included in all copies and derivative works. The condition is satisfied."
    - message: "commercial license LicenseRef-scancode-proprietary-license in Maven:com.sun.xml.ws:policy:.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The declared license is actually BSD-3-Clause."
    - message: "proprietary-free license LicenseRef-scancode-sun-prop-non-commercial in Maven:antlr:antlr:2.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The license LicenseRef-scancode-sun-prop-non-commercial allows use, copying, modification, and redistribution of the software and its documentation for non-commercial purposes, provided that the copyright notice is included in all copies. The condition is satisfied."

curations:
  license_findings:
    - path: "Core/Domibus-MSH/src/main/resources/config/infinispan/domibus-infinispan-default.xml"
      concluded_license: "LGPL-2.1-or-later"
      reason: "INCORRECT"
      comment: "Corrected scanner finding."

license_choices:
  repository_license_choices:
    - given: "LGPL-2.1-only OR EPL-1.0"
      choice: "LGPL-2.1-only"
    - given: "BSD-3-Clause AND Apache-2.0 AND W3C AND LicenseRef-Public-domain AND MIT AND Apache-1.1 AND SAX-PD AND (MIT OR GPL-1.0-or-later) AND EPL-1.0"
      choice: "BSD-3-Clause AND Apache-2.0 AND W3C AND LicenseRef-Public-domain AND MIT AND Apache-1.1 AND SAX-PD AND MIT AND EPL-1.0"
    - given: "CDDL-1.0 OR GPL-2.0-only WITH Classpath-exception-2.0"
      choice: "GPL-2.0-only WITH Classpath-exception-2.0"
    - given: "BSD-3-Clause AND Apache-2.0 AND (GPL-2.0-only OR GPL-2.0-only WITH Classpath-exception-2.0) AND MIT"
      choice: "BSD-3-Clause AND Apache-2.0 AND GPL-2.0-only WITH Classpath-exception-2.0 AND MIT"
    - given: "BSD-3-Clause AND Apache-2.0 AND W3C AND LicenseRef-scancode-public-domain AND MIT AND SAX-PD AND EPL-1.0 AND (Apache-2.0 OR Apache-1.1 OR BSD-3-Clause OR LicenseRef-scancode-public-domain OR LicenseRef-scancode-indiana-extreme) AND (MIT OR GPL-1.0-or-later)"
      choice: "BSD-3-Clause AND Apache-2.0 AND W3C AND LicenseRef-scancode-public-domain AND MIT AND SAX-PD AND EPL-1.0 AND BSD-3-Clause AND MIT"
