package eu.domibus.plugin.webService.logging;

import org.apache.cxf.ext.logging.event.LogEvent;

/**
 * Business to strip the payload generated by apache cxf - WS Plugin
 *
 * @since 4.1.4
 * @author Catalin Enache
 */
public interface WSPluginLoggingEventHelper {

    void stripPayload(LogEvent logEvent);

    String checkIfOperationIsAllowed(LogEvent logEvent);
}
