<?xml version="1.0" encoding="UTF-8"?>

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.niis</groupId>
        <artifactId>core</artifactId>
        <version>2.6.1</version>
    </parent>

    <artifactId>harmony-archive-webhook-swagger</artifactId>
    <packaging>war</packaging>
    <name>Harmony eArchive webhook swagger definition</name>
    <properties>
        <openapi.output>${project.build.directory}/generated-sources</openapi.output>
        <generator.resourcesDirectory>${basedir}/src/main/resources/</generator.resourcesDirectory>
        <openapi.output.document>domibus-archive-webhook-openapi</openapi.output.document>
        <upstream.url>https://github.com/swagger-api/swagger-ui/archive/v${swagger-ui.version}.zip</upstream.url>
    </properties>
    <dependencies>

        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-annotations</artifactId>
        </dependency>
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-jaxrs2</artifactId>
        </dependency>
        <dependency>
            <groupId>javax.ws.rs</groupId>
            <artifactId>javax.ws.rs-api</artifactId>
        </dependency>
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
        </dependency>
    </dependencies>


    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
            <!-- Generate openApi document -->
            <plugin>
                <groupId>io.swagger.core.v3</groupId>
                <artifactId>swagger-maven-plugin</artifactId>
                <configuration>
                    <outputFileName>${openapi.output.document}</outputFileName>
                    <outputPath>${generator.resourcesDirectory}</outputPath>
                    <outputFormat>JSON</outputFormat>
                    <resourcePackages>
                        <package>eu.domibus.archive.client.webhook</package>
                    </resourcePackages>
                    <prettyPrint>true</prettyPrint>
                </configuration>
                <executions>
                    <execution>
                        <phase>compile</phase>
                        <goals>
                            <goal>resolve</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <!-- copy generated OpenApi document the earchive client -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-resource-openAPI-Document</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${openapi.output}</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${generator.resourcesDirectory}</directory>
                                    <includes>
                                        <include>${openapi.output.document}.json</include>
                                    </includes>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!-- to make sure opeapi document is generated -->
            <plugin>
                <artifactId>maven-enforcer-plugin</artifactId>
                <executions>
                    <execution>
                        <id>enforce-files</id>
                        <phase>install</phase>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <requireFilesExist>
                                    <files>
                                        <file>${openapi.output}/${openapi.output.document}.json</file>
                                    </files>
                                </requireFilesExist>
                            </rules>
                            <fail>true</fail>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <profiles>
        <profile>
            <id>license-generate-notice</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>license-maven-plugin</artifactId>
                        <configuration>
                            <licenseResolver>${project.baseUri}../../license</licenseResolver>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>swagger</id>
            <build>
                <plugins>
                    <!-- Purpose of the ANT plugin is to download and extract swagger-ui pages to folder ${project.basedir}/src/main/webapp-->
                    <plugin>
                        <artifactId>maven-antrun-plugin</artifactId>
                        <executions>
                            <execution>
                                <phase>process-resources</phase>
                                <goals>
                                    <goal>run</goal>
                                </goals>
                                <configuration>
                                    <target>
                                        <!-- download and extract swagger-ui scripts/html pages -->
                                        <echo message="download archive"/>
                                        <get src="${upstream.url}" dest="${project.build.directory}/${project.artifactId}.zip"/>
                                        <echo message="unzip archive"/>
                                        <unzip src="${project.build.directory}/${project.artifactId}.zip"
                                               dest="${project.build.directory}"/>
                                        <echo message="moving resources"/>
                                        <move todir="${openapi.output}">
                                            <fileset dir="${project.build.directory}/swagger-ui-${swagger-ui.version}/dist"/>
                                        </move>
                                        <echo message="Set openapi.json as default file (openapi.json is generated in test OpenApiGenerator.java)"/>
                                        <replace file="${openapi.output}/swagger-initializer.js"
                                                 token="https://petstore.swagger.io/v2/swagger.json" value="domibus-archive-webhook-openapi.json" />
                                        <replace file="${openapi.output}/swagger-ui.js"
                                                 token="https://petstore.swagger.io/v2/swagger.json" value="domibus-archive-webhook-openapi.json" />
                                        <!-- generate openAPI document using springdoc -->
                                        <!-- start maven plugin with java instead of mvn because some maven applications does not have execute permission as example
                                           maven in intellij -->
                                        <exec dir="${project.basedir}" executable="${java.home}/bin/java">
                                            <arg value="-cp"/>
                                            <!--suppress UnresolvedMavenProperty -->
                                            <arg value='${maven.home}/boot/*'/>
                                            <!--suppress UnresolvedMavenProperty -->
                                            <arg value="-Dmaven.multiModuleProjectDirectory=${maven.multiModuleProjectDirectory}" />
                                            <!--suppress UnresolvedMavenProperty -->
                                            <arg value="-Dmaven.home=${maven.home}" />
                                            <!--suppress UnresolvedMavenProperty -->
                                            <arg value="-Dclassworlds.conf=${maven.home}/bin/m2.conf" />
                                            <arg value="-Dfile.encoding=UTF-8" />
                                            <arg value="-Dproject.reporting.outputEncoding=UTF-8" />
                                            <arg value="org.codehaus.classworlds.Launcher" />
                                            <arg value="org.apache.maven.plugins:maven-failsafe-plugin:${maven-failsafe-plugin.version}:integration-test" />
                                            <arg value="-Dit.test=OpenApiGenerator" />
                                        </exec>
                                    </target>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <!-- build war artefacts with swagger-ui -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-war-plugin</artifactId>
                        <configuration>
                            <webappDirectory>${openapi.output}</webappDirectory>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>