-- *********************************************************************
-- Delete script for MySQL Domibus DB with a time interval
-- Change START_DATE and END_DATE values accordingly - please pay attention
-- that the data stored in DB is timezone agnostic.
--
-- Important: In order to keep the JMS queues synchronized with the DB data that will be
-- deleted by this script, the Domibus Administrator should remove manually the associated
-- JMS messages from the plugin notifications queues
-- *********************************************************************
SET @START_DATE = STR_TO_DATE('2021-08-10 10:00:00', '%Y-%m-%d %H:%i:%s');
SET @END_DATE = STR_TO_DATE('2022-04-29 15:00:00', '%Y-%m-%d %H:%i:%s');

SET @OLD_SQL_SAFE_UPDATES = @@SQL_SAFE_UPDATES;
SET SQL_SAFE_UPDATES = 0;

DELETE
FROM TB_USER_MESSAGE_LOG
WHERE (ID_PK IN (SELECT ID_PK
                 FROM TB_USER_MESSAGE
                 WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE));

DELETE
FROM TB_USER_MESSAGE_RAW
WHERE (ID_PK IN (SELECT ID_PK
                 FROM TB_USER_MESSAGE
                 WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE));


DELETE
FROM TB_SIGNAL_MESSAGE_RAW
WHERE (ID_PK IN (SELECT ID_PK
                 FROM TB_SIGNAL_MESSAGE
                 WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE));

DELETE
FROM TB_SIGNAL_MESSAGE_LOG
WHERE (ID_PK IN (SELECT ID_PK
                 FROM TB_SIGNAL_MESSAGE

                 WHERE ID_PK IN (SELECT ID_PK
                                 FROM TB_USER_MESSAGE

                                 WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE)));
DELETE
FROM TB_RECEIPT
WHERE (ID_PK IN (SELECT ID_PK
                 FROM TB_SIGNAL_MESSAGE

                 WHERE ID_PK IN (SELECT ID_PK
                                 FROM TB_USER_MESSAGE

                                 WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE)));

DELETE
FROM TB_SIGNAL_MESSAGE

WHERE ID_PK IN (SELECT ID_PK
                FROM TB_USER_MESSAGE

                WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE);



DELETE
FROM TB_ERROR_LOG
WHERE (ERROR_SIGNAL_MESSAGE_ID IN (SELECT MESSAGE_ID
                                   FROM TB_USER_MESSAGE

                                   WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE));

DELETE
FROM TB_ERROR_LOG
WHERE (MESSAGE_IN_ERROR_ID IN (SELECT MESSAGE_ID
                               FROM TB_USER_MESSAGE

                               WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE));

DELETE
FROM TB_SJ_MESSAGE_HEADER
WHERE (ID_PK IN (SELECT ID_PK
                 FROM TB_SJ_MESSAGE_GROUP
                 WHERE (SOURCE_MESSAGE_ID_FK IN (SELECT ID_PK
                                                 FROM TB_USER_MESSAGE

                                                 WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE))));

DELETE
FROM TB_SJ_MESSAGE_FRAGMENT
WHERE (GROUP_ID_FK IN (SELECT ID_PK
                       FROM TB_SJ_MESSAGE_GROUP

                       WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE));

DELETE
FROM TB_SJ_MESSAGE_GROUP
WHERE (SOURCE_MESSAGE_ID_FK IN (SELECT ID_PK
                                FROM TB_USER_MESSAGE

                                WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE));

DELETE
FROM TB_SJ_MESSAGE_FRAGMENT
WHERE (ID_PK IN (SELECT ID_PK
                 FROM TB_USER_MESSAGE

                 WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE));

DELETE
FROM TB_PART_PROPERTIES tpp
WHERE tpp.PART_INFO_ID_FK IN (
    SELECT tpi.ID_PK
    FROM TB_PART_INFO tpi
    WHERE tpi.USER_MESSAGE_ID_FK IN (
        SELECT tu.ID_PK
        FROM TB_USER_MESSAGE tu
        WHERE tu.CREATION_TIME BETWEEN @START_DATE AND @END_DATE));

DELETE
FROM TB_PART_INFO tpi
WHERE tpi.USER_MESSAGE_ID_FK IN (
    SELECT tu.ID_PK
    FROM TB_USER_MESSAGE tu
    WHERE tu.CREATION_TIME BETWEEN @START_DATE AND @END_DATE);

DELETE
FROM tb_send_attempt
WHERE USER_MESSAGE_ID_FK IN (
    SELECT ID_PK
    FROM TB_USER_MESSAGE
    WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE);

DELETE
FROM TB_MESSAGE_ACKNW_PROP
WHERE FK_MSG_ACKNOWLEDGE IN (
    SELECT ID_PK
    FROM TB_MESSAGE_ACKNW
    WHERE USER_MESSAGE_ID_FK IN (
        SELECT ID_PK
        FROM TB_USER_MESSAGE
        WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE));

DELETE
FROM TB_MESSAGE_ACKNW
WHERE USER_MESSAGE_ID_FK IN (
    SELECT ID_PK
    FROM TB_USER_MESSAGE
    WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE);

DELETE
FROM TB_MESSAGING_LOCK
WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE;

DELETE
FROM TB_MESSAGE_PROPERTIES
WHERE USER_MESSAGE_ID_FK IN (
    SELECT ID_PK
    FROM TB_USER_MESSAGE
    WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE);

DELETE
FROM TB_USER_MESSAGE
WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE AND ID_PK NOT IN('19700101');

DELETE
FROM TB_EARCHIVE_START
WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE;

DELETE
FROM TB_EARCHIVE_BATCH
WHERE (BATCH_ID IN (SELECT FK_EARCHIVE_BATCH_ID
                 FROM TB_EARCHIVEBATCH_UM
                 WHERE FK_USER_MESSAGE_ID IN (SELECT ID_PK
                                         FROM TB_USER_MESSAGE
                                         WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE)));

DELETE
FROM TB_EARCHIVEBATCH_UM
WHERE FK_USER_MESSAGE_ID IN (SELECT ID_PK
                             FROM TB_USER_MESSAGE
                             WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE)));

DELETE
FROM WS_PLUGIN_TB_BACKEND_MSG_LOG
WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE;

DELETE
FROM WS_PLUGIN_TB_MESSAGE_LOG
WHERE RECEIVED BETWEEN @START_DATE AND @END_DATE;

SET SQL_SAFE_UPDATES = @OLD_SQL_SAFE_UPDATES;

COMMIT;