-- *********************************************************************
-- Delete script for Oracle Domibus DB with a time interval
-- Change START_DATE and END_DATE values accordingly - please pay attention
-- that the data stored in DB is timezone agnostic.
--
-- Important: In order to keep the JMS queues synchronized with the DB data that will be
-- deleted by this script, the Domibus Administrator should remove manually the associated
-- JMS messages FROM the plugin notifications queues
-- *********************************************************************

/* For SQL*Plus client use specific definition like:
   variable START_DATE varchar2(30)
   exec :START_DATE := '2013-10-01';
*/
DEFINE START_DATE = TO_DATE('08-SEP-2021 09:59:00', 'DD-MM-YY HH24:MI:SS');
DEFINE END_DATE = TO_DATE('04-MAY-2022 10:00:00', 'DD-MM-YY HH24:MI:SS');

DELETE
FROM TB_USER_MESSAGE_LOG
WHERE (ID_PK IN (SELECT ID_PK
                 FROM TB_USER_MESSAGE
                 WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE));

DELETE
FROM TB_USER_MESSAGE_RAW
WHERE (ID_PK IN (SELECT ID_PK
                 FROM TB_USER_MESSAGE
                 WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE));


DELETE
FROM TB_SIGNAL_MESSAGE_RAW
WHERE (ID_PK IN (SELECT ID_PK
                 FROM TB_SIGNAL_MESSAGE
                 WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE));

DELETE
FROM TB_SIGNAL_MESSAGE_LOG
WHERE (ID_PK IN (SELECT ID_PK
                 FROM TB_SIGNAL_MESSAGE

                 WHERE ID_PK IN (SELECT ID_PK
                                 FROM TB_USER_MESSAGE

                                 WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE)));
DELETE
FROM TB_RECEIPT
WHERE (ID_PK IN (SELECT ID_PK
                 FROM TB_SIGNAL_MESSAGE

                 WHERE ID_PK IN (SELECT ID_PK
                                 FROM TB_USER_MESSAGE

                                 WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE)));

DELETE
FROM TB_SIGNAL_MESSAGE

WHERE ID_PK IN (SELECT ID_PK
                FROM TB_USER_MESSAGE

                WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE);



DELETE
FROM TB_ERROR_LOG
WHERE (ERROR_SIGNAL_MESSAGE_ID IN (SELECT MESSAGE_ID
                                   FROM TB_USER_MESSAGE

                                   WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE));

DELETE
FROM TB_ERROR_LOG
WHERE (MESSAGE_IN_ERROR_ID IN (SELECT MESSAGE_ID
                               FROM TB_USER_MESSAGE

                               WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE));

DELETE
FROM TB_SJ_MESSAGE_HEADER
WHERE (ID_PK IN (SELECT ID_PK
                 FROM TB_SJ_MESSAGE_GROUP
                 WHERE (SOURCE_MESSAGE_ID_FK IN (SELECT ID_PK
                                                 FROM TB_USER_MESSAGE

                                                 WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE))));

DELETE
FROM TB_SJ_MESSAGE_FRAGMENT
WHERE (GROUP_ID_FK IN (SELECT ID_PK
                       FROM TB_SJ_MESSAGE_GROUP

                       WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE));

DELETE
FROM TB_SJ_MESSAGE_GROUP
WHERE (SOURCE_MESSAGE_ID_FK IN (SELECT ID_PK
                                FROM TB_USER_MESSAGE

                                WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE));

DELETE
FROM TB_SJ_MESSAGE_FRAGMENT
WHERE (ID_PK IN (SELECT ID_PK
                 FROM TB_USER_MESSAGE

                 WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE));

DELETE
FROM TB_PART_PROPERTIES tpp
WHERE tpp.PART_INFO_ID_FK IN (
    SELECT tpi.ID_PK
    FROM TB_PART_INFO tpi
    WHERE tpi.USER_MESSAGE_ID_FK IN (
        SELECT tu.ID_PK
        FROM TB_USER_MESSAGE tu
        WHERE tu.CREATION_TIME BETWEEN @START_DATE AND @END_DATE));

DELETE
FROM TB_PART_INFO tpi
WHERE tpi.USER_MESSAGE_ID_FK IN (
    SELECT tu.ID_PK
    FROM TB_USER_MESSAGE tu
    WHERE tu.CREATION_TIME BETWEEN @START_DATE AND @END_DATE);

DELETE
FROM tb_send_attempt
WHERE USER_MESSAGE_ID_FK IN (
    SELECT ID_PK
    FROM TB_USER_MESSAGE
    WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE);

DELETE
FROM TB_MESSAGE_ACKNW_PROP
WHERE FK_MSG_ACKNOWLEDGE IN (
    SELECT ID_PK
    FROM TB_MESSAGE_ACKNW
    WHERE USER_MESSAGE_ID_FK IN (
        SELECT ID_PK
        FROM TB_USER_MESSAGE
        WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE));

DELETE
FROM TB_MESSAGE_ACKNW
WHERE USER_MESSAGE_ID_FK IN (
    SELECT ID_PK
    FROM TB_USER_MESSAGE
    WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE);

DELETE
FROM TB_MESSAGING_LOCK
WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE;

DELETE
FROM TB_MESSAGE_PROPERTIES
WHERE USER_MESSAGE_ID_FK IN (
    SELECT ID_PK
    FROM TB_USER_MESSAGE
    WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE);

DELETE
FROM TB_USER_MESSAGE
WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE AND ID_PK NOT IN(19700101);

DELETE
FROM WS_PLUGIN_TB_BACKEND_MSG_LOG
WHERE CREATION_TIME BETWEEN @START_DATE AND @END_DATE;

DELETE
FROM WS_PLUGIN_TB_MESSAGE_LOG
WHERE RECEIVED BETWEEN @START_DATE AND @END_DATE;

COMMIT;
