ALTER TABLE TB_MESSAGE_ACKNW MODIFY PARTITION BY REFERENCE ( FK_MSG_ACK_USER_MSG );

ALTER TABLE TB_MESSAGE_ACKNW_PROP MODIFY PARTITION BY REFERENCE ( FK_MSG_ACK_PROP_MSG_ACK );

ALTER TABLE TB_SJ_MESSAGE_GROUP MODIFY PARTITION BY REFERENCE ( FK_MSG_FG_GROUP_UM ) UPDATE INDEXES ( IDX_SJ_MG_ROLE_FK LOCAL );

ALTER TABLE TB_SJ_MESSAGE_FRAGMENT MODIFY PARTITION BY REFERENCE ( FK_SJ_MSG_FG_USER_MSG ) UPDATE INDEXES ( IDX_FK_SJ_MSG_FG_GROUP LOCAL );

ALTER TABLE TB_USER_MESSAGE_LOG MODIFY PARTITION BY REFERENCE ( FK_MSG_LOG_MSG_ID ) UPDATE INDEXES ( IDX_USER_LOG_RECEIVED LOCAL, IDX_MESSAGE_LOG_TZ_OFFSET LOCAL, IDX_MSG_ARCHIVED LOCAL, IDX_MSG_EXPORTED LOCAL, IDX_MSG_ACKNOWLEDGED LOCAL, IDX_MSG_PROCESSING_TYPE LOCAL, IDX_MESSAGE_LOG_MSG_STATUS_ID LOCAL, IDX_MESSAGE_LOG_MSG_ROLE_ID LOCAL, IDX_MSG_LOG_NOTIF_STATUS_ID LOCAL );

ALTER TABLE TB_PART_INFO MODIFY PARTITION BY REFERENCE ( FK_PART_INFO_USER_MSG );

ALTER TABLE TB_PART_PROPERTIES MODIFY PARTITION BY REFERENCE ( FK_PART_PROPS_PART_INFO ) UPDATE INDEXES ( IDX_PART_PROPS_PART_PROP LOCAL );

ALTER TABLE TB_MESSAGE_PROPERTIES MODIFY PARTITION BY REFERENCE ( FK_MSG_PROPS_USER_MSG );

ALTER TABLE TB_USER_MESSAGE_RAW MODIFY PARTITION BY REFERENCE ( FK_MSG_RAW_USER_MSG );

ALTER TABLE TB_SIGNAL_MESSAGE MODIFY PARTITION BY REFERENCE ( FK_TB_SIGNAL_USER_MSG ) UPDATE INDEXES ( IDX_SIG_MESS_REF_TO_MESS_ID LOCAL, IDX_SIG_MESS_SIGNAL_MESS_ID LOCAL );

ALTER TABLE TB_SIGNAL_MESSAGE_LOG MODIFY PARTITION BY REFERENCE ( FK_SIGNAL_LOG_SIGNAL_ID ) UPDATE INDEXES ( IDX_SIGNAL_LOG_MSG_STATUS_ID LOCAL, IDX_SIGNAL_LOG_MSG_ROLE_ID LOCAL, IDX_SIGNAL_LOG_RECEIVED LOCAL );

ALTER TABLE TB_RECEIPT MODIFY PARTITION BY REFERENCE ( FK_TB_RECEIPT_SIGNAL_MSG );

ALTER TABLE TB_SIGNAL_MESSAGE_RAW MODIFY PARTITION BY REFERENCE ( FK_SIGNAL_MSG_RAW_SIGNAL_MSG );

ALTER TABLE TB_SEND_ATTEMPT MODIFY PARTITION BY REFERENCE ( FK_SEND_ATTEMPT_USER_MSG );

ALTER TABLE TB_ERROR_LOG MODIFY PARTITION BY REFERENCE ( FK_ERROR_LOG_MSG_ID ) UPDATE INDEXES ( IDX_ERROR_LOG_MSH_ROLE_ID LOCAL, IDX_MESSAGE_IN_ERROR_ID LOCAL, IDX_SIGNAL_MESSAGE_ID LOCAL );
