package eu.domibus.ext.domain.archive;

/**
 * @author Joze Rihtarsic
 * @since 5.0
 */
public enum BatchRequestType {
    /**
     * Describe the batches generated by the eArchive jobs in the context of continuous archiving
     */
    CONTINUOUS,

    /**
     * Describe the batches generated by API calls in the context of a ponctual archiving
     */
    MANUAL,
    /**
     * Missed messages - from the client perspective this is also "CONTINUOUS"
     */
    SANITIZER

}
