<?xml version="1.0" encoding="UTF-8"?>

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.niis</groupId>
        <artifactId>plugin-jms</artifactId>
        <version>2.7.0-SNAPSHOT</version>
    </parent>

    <artifactId>harmony-default-jms-plugin</artifactId>
    <packaging>jar</packaging>
    <name>Harmony MSH Default JMS Plugin</name>

    <dependencies>
        <dependency>
            <groupId>org.niis</groupId>
            <artifactId>harmony-ext-model</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.niis</groupId>
            <artifactId>harmony-plugin-api</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.activemq</groupId>
            <artifactId>activemq-client</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-collections4</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.niis</groupId>
            <artifactId>harmony-logging</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-beans</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-tx</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-jms</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.activation</groupId>
            <artifactId>jakarta.activation-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
        </dependency>
        <dependency>
            <groupId>io.dropwizard.metrics</groupId>
            <artifactId>metrics-core</artifactId>
            <scope>provided</scope>
        </dependency>
        <!--        Start TEST        -->
        <dependency>
            <groupId>org.jmockit</groupId>
            <artifactId>jmockit</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.niis</groupId>
            <artifactId>harmony-msh-test</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.niis</groupId>
            <artifactId>harmony-msh-test-common</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.glassfish</groupId>
            <artifactId>javax.el</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.niis</groupId>
            <artifactId>harmony-MSH-tomcat</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <!--        End TEST        -->

    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <executions>
                    <execution>
                        <id>enforce-banned-dependencies</id>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <bannedDependencies>
                                    <searchTransitive>false</searchTransitive>
                                    <excludes>
                                        <exclude>org.niis:*</exclude>
                                    </excludes>
                                    <includes>
                                        <include>org.niis:harmony-plugin-api</include>
                                        <include>org.niis:harmony-ext-model</include>
                                        <include>org.niis:harmony-logging</include>
                                        <include>org.niis:harmony-msh-test-common</include>
                                        <include>org.niis:harmony-msh-test</include>
                                        <include>org.niis:harmony-MSH-tomcat:${project.version}:jar:test</include>
                                    </includes>
                                </bannedDependencies>
                            </rules>
                            <fail>true</fail>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>tomcat</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-enforcer-plugin</artifactId>
                        <dependencies>
                            <dependency>
                                <groupId>org.niis</groupId>
                                <artifactId>harmony-msh-test-common</artifactId>
                                <version>${project.version}</version>
                            </dependency>
                            <dependency>
                                <groupId>org.niis</groupId>
                                <artifactId>harmony-logging</artifactId>
                                <version>${project.version}</version>
                            </dependency>

                            <!-- needed to get the server dependencies from the classes directory -->
                            <dependency>
                                <groupId>org.niis</groupId>
                                <artifactId>harmony-MSH-tomcat-distribution</artifactId>
                                <version>${project.version}</version>
                                <classifier>classes</classifier>
                            </dependency>
                        </dependencies>
                        <executions>
                            <execution>
                                <id>enforce-no-duplicate-dependencies-tomcat</id>
                                <phase>test</phase>
                                <goals>
                                    <goal>enforce</goal>
                                </goals>
                                <configuration>
                                    <rules>
                                        <duplicateDependenciesRule>
                                            <equivalentDuplicateDependencies>
                                                <item>bcpkix-jdk15on,bcpkix-jdk18on,bcpkix-jdk15to18</item>
                                                <item>bcutil-jdk15on,bcutil-jdk18on,bcutil-jdk15to18</item>
                                                <item>bcprov-jdk15on,bcprov-jdk18on,bcprov-jdk15to18</item>
                                            </equivalentDuplicateDependencies>

                                            <checkAgainstServerDependencies>
                                                <item>tomcat</item>
                                            </checkAgainstServerDependencies>
                                        </duplicateDependenciesRule>
                                    </rules>
                                    <fail>true</fail>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>weblogic</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-enforcer-plugin</artifactId>
                        <dependencies>
                            <dependency>
                                <groupId>org.niis</groupId>
                                <artifactId>harmony-msh-test-common</artifactId>
                                <version>${project.version}</version>
                            </dependency>
                            <dependency>
                                <groupId>org.niis</groupId>
                                <artifactId>harmony-logging</artifactId>
                                <version>${project.version}</version>
                            </dependency>

                            <!-- needed to get the server dependencies from the classes directory -->
                            <dependency>
                                <groupId>org.niis</groupId>
                                <artifactId>harmony-MSH-weblogic</artifactId>
                                <version>${project.version}</version>
                                <classifier>classes</classifier>
                            </dependency>
                        </dependencies>
                        <executions>
                            <execution>
                                <id>enforce-no-duplicate-dependencies-weblogic</id>
                                <phase>test</phase>
                                <goals>
                                    <goal>enforce</goal>
                                </goals>
                                <configuration>
                                    <rules>
                                        <duplicateDependenciesRule>
                                            <equivalentDuplicateDependencies>
                                                <item>bcpkix-jdk15on,bcpkix-jdk18on,bcpkix-jdk15to18</item>
                                                <item>bcutil-jdk15on,bcutil-jdk18on,bcutil-jdk15to18</item>
                                                <item>bcprov-jdk15on,bcprov-jdk18on,bcprov-jdk15to18</item>
                                            </equivalentDuplicateDependencies>

                                            <checkAgainstServerDependencies>
                                                <item>weblogic</item>
                                            </checkAgainstServerDependencies>
                                        </duplicateDependenciesRule>
                                    </rules>
                                    <fail>true</fail>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>wildfly</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-enforcer-plugin</artifactId>
                        <dependencies>
                            <dependency>
                                <groupId>org.niis</groupId>
                                <artifactId>harmony-msh-test-common</artifactId>
                                <version>${project.version}</version>
                            </dependency>
                            <dependency>
                                <groupId>org.niis</groupId>
                                <artifactId>harmony-logging</artifactId>
                                <version>${project.version}</version>
                            </dependency>

                            <!-- needed to get the server dependencies from the classes directory -->
                            <dependency>
                                <groupId>org.niis</groupId>
                                <artifactId>harmony-MSH-wildfly</artifactId>
                                <version>${project.version}</version>
                                <classifier>classes</classifier>
                            </dependency>
                        </dependencies>
                        <executions>
                            <execution>
                                <id>enforce-no-duplicate-dependencies-wildfly</id>
                                <phase>test</phase>
                                <goals>
                                    <goal>enforce</goal>
                                </goals>
                                <configuration>
                                    <rules>
                                        <duplicateDependenciesRule>
                                            <equivalentDuplicateDependencies>
                                                <item>bcpkix-jdk15on,bcpkix-jdk18on,bcpkix-jdk15to18</item>
                                                <item>bcutil-jdk15on,bcutil-jdk18on,bcutil-jdk15to18</item>
                                                <item>bcprov-jdk15on,bcprov-jdk18on,bcprov-jdk15to18</item>
                                            </equivalentDuplicateDependencies>

                                            <checkAgainstServerDependencies>
                                                <item>wildfly</item>
                                            </checkAgainstServerDependencies>
                                        </duplicateDependenciesRule>
                                    </rules>
                                    <fail>true</fail>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>license-generate-notice</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>license-maven-plugin</artifactId>
                        <configuration>
                            <licenseResolver>${project.baseUri}../../license</licenseResolver>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
